Добавлены режиссеры к фильмам
Hivludi/java-filmorate pull request #19
Opened 2023-03-05 17:19 UTC by ChertkovFedor

### API

`GET /films/director/{directorId}?sortBy=[year,likes]` 

Возвращает список фильмов режиссера отсортированных по количеству лайков или году выпуска. 

`POST /films`

```json
{
	"name": "New film",
	"releaseDate": "1999-04-30",
	"description": "New film about friends",
	"duration": 120,
	"mpa": { "id": 3},
	"genres": [{ "id": 1}],
	"director": [{ "id": 1}]
}

```

`GET /directors` - Список всех режиссёров

`GET /directors/{id}`- Получение режиссёра по id

`POST /directors` - Создание режиссёра

`PUT /directors` - Изменение режиссёра

```json
{
"id": 1,
"name": "New director"
}
```

`DELETE /directors/{id}` - Удаление режиссёра

2023-03-05 18:24 UTC, alex1056 requested changes

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        directorService.delete(directorId);
Здесь надо возвращать удаленный объект

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.deleteFilmById(filmId);
надо возвращать удаленный объект

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (directorDao.getDirectorById(director.getId()).isPresent()) return directorDao.update(director);
У нас по архитектуре других методов эксепшен НЕ НАЙДЕН, в данном случае ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", director.getId()));
Убран внутрь метода getDirectorById - так меньше повторяемого когда.

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        else throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
Одно и тоже повторяем из метода в метод

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDao.java
> +        return getDirectorById(directorId).isEmpty();
Надо возвращать объект удаленного директора

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDao.java
> +    public Set<Director> listDirectorByFilmId(long filmId) {
А зачем нам Set, можно обычным List возвращать

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Director d : film.getDirectors()) {
Одним запросом можно сделать?

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId))
надо перенести внутрь directorDao.getDirectorById

2023-03-05 18:24 UTC, alex1056 commented on src/main/resources/schema.sql
> +    constraint FILMS_PK
Добавить IF NOT EXISTS

2023-03-05 18:24 UTC, alex1056 commented on src/main/resources/schema.sql
> +    constraint FILMS_MPA_MPA_ID_FK
добавить IF NOT EXISTS

2023-03-05 18:24 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          filmStorage.deleteFilmById(filmId);
надо возвращать удаленный объект

2023-03-06 09:10 UTC, Hivludi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Director d : film.getDirectors()) {
Мне кажется тут не получится одним запросом, так как мы инсертим всех директоров, если их больше одного, соответственно будет несколько запросов

2023-03-06 09:11 UTC, Hivludi commented on src/main/resources/schema.sql
> - create table IF NOT EXISTS GENRES
Жанры удалять не надо

2023-03-06 10:20 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Director d : film.getDirectors()) {
Надо через Стрингбилдер собрать все что надо и на выходе из цикла сделать один insert

2023-03-06 13:56 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        directorService.delete(directorId);
В delete везде убрал возврат каких либо данных

2023-03-06 13:56 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          filmService.deleteFilmById(filmId);
В delete везде убрал возврат каких либо данных

2023-03-06 13:57 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (directorDao.getDirectorById(director.getId()).isPresent()) return directorDao.update(director);
Перенес эксепшен в getDirectorById

2023-03-06 13:57 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        else throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
Перенес эксепшен в getDirectorById

2023-03-06 13:57 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDao.java
> +        return getDirectorById(directorId).isEmpty();
В delete везде убрал возврат каких либо данных

2023-03-06 14:00 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            for (Director d : film.getDirectors()) {
Организовал процесс через Стрингбилдер. 
Так же привел к аналогичному виду жанры и лайки. 
Вынес повторяющийся код из create и update методов фильма в отдельный внутренний метод.

2023-03-06 14:00 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
Перенес эксепшен в getDirectorById

2023-03-06 14:01 UTC, ChertkovFedor commented on src/main/resources/schema.sql
> +    constraint FILMS_PK
IF NOT EXISTS добавил

2023-03-06 14:01 UTC, ChertkovFedor commented on src/main/resources/schema.sql
> +    constraint FILMS_MPA_MPA_ID_FK
IF NOT EXISTS добавил

2023-03-06 14:01 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          filmStorage.deleteFilmById(filmId);
В delete везде убрал возврат каких либо данных

2023-03-06 14:01 UTC, ChertkovFedor commented on src/main/resources/schema.sql
> - create table IF NOT EXISTS GENRES
Жанры создаются позже

2023-03-06 15:37 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
Наверное ты его забыл убрать здесь.

2023-03-07 02:48 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDao.java
> +    public Set<Director> listDirectorByFilmId(long filmId) {
Поменял на List

2023-03-07 08:57 UTC, ChertkovFedor commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Режиссёр с идентификатором %s не найден", directorId));
Убрал

2023-03-07 09:44 UTC, alex1056 approved these changes

2023-03-07 09:45 UTC, Hivludi approved these changes

2023-03-07 09:46 UTC, merged