Add feed
Hivludi/java-filmorate pull request #23
Opened 2023-03-06 23:41 UTC by Fytonzo

create: Полностью реализован функционал ленты событий

2023-03-06 23:46 UTC, Fytonzo commented
Постмановские тесты падают потому что в одном из них ошибка, конкретно в тесте Review update to positive вместо "userId": 2, должно быть "userId": 1, при локальной замене все тесты проходят успешно, возможно ошибка допущена специально. Этот ошибка затрагивает тесты только для данного функционал.

2023-03-07 08:56 UTC, alex1056 requested changes

2023-03-07 08:56 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> opt = reviewStorage.create(review);
Вообще принято давать осознанные имена переменным. Может дольше писать, но сразу понятно будет reviewOptional, чем opt

2023-03-07 08:56 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            Review review1 = opt.get();
А здесь не review1, а reviewCreated.

2023-03-07 08:56 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDao.java
> +    private boolean userExistInDb(Integer id){
Считаю метод лишним, у нас за поиск пользователя в базе отвечает findUserById, он уже содержит throw если юзера нет

2023-03-07 08:56 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDao.java
> +    private boolean entityExistInDb(FeedEvent feedEvent) {
может его назвать более по человечески, типа isFeedEventExist (Db лучше опустить, т.к. это само собой разумеющееся)

2023-03-07 08:59 UTC, alex1056 commented
По тестам - это те же тесты что и локально мы тестируем, можно проследить откуда он их берет - те же тесты. Значит надо еще поискать что не так.

2023-03-07 17:46 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> opt = reviewStorage.create(review);
исправлено

2023-03-07 17:46 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            Review review1 = opt.get();
исправлено

2023-03-07 17:46 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDao.java
> +    private boolean userExistInDb(Integer id){
заменил на find из UserDbStorage

2023-03-07 17:46 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDao.java
> +    private boolean entityExistInDb(FeedEvent feedEvent) {
исправлено

2023-03-07 18:20 UTC, Hivludi approved these changes

2023-03-07 18:44 UTC, alex1056 approved these changes

2023-03-07 18:47 UTC, merged